DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'shield_runtime') THEN
    CREATE ROLE shield_runtime LOGIN PASSWORD 'shield_runtime_test_only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END $$;
GRANT CONNECT ON DATABASE shield TO shield_runtime;
GRANT USAGE ON SCHEMA public TO shield_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO shield_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO shield_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO shield_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO shield_runtime;
